-- CreateTable
CREATE TABLE "SampleData" (
    "id" SERIAL NOT NULL,
    "sampleCode" TEXT NOT NULL,
    "sampleItemName" TEXT NOT NULL,
    "processingType" TEXT NOT NULL,
    "constructionNote" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "customerName" TEXT NOT NULL,
    "customerRequirementWidthPercent" TEXT NOT NULL,
    "customerRequirementLengthPercent" TEXT NOT NULL,
    "customerRequirementWidth" TEXT NOT NULL,
    "requirementWeight" TEXT NOT NULL,
    "finishingDate" TEXT NOT NULL,
    "loom" INTEGER NOT NULL,
    "warpingNo" INTEGER NOT NULL,
    "yard" INTEGER NOT NULL,
    "afterDryerWidth" TEXT NOT NULL,
    "weavingPPI" INTEGER NOT NULL,
    "sanforizedPPI" INTEGER NOT NULL,
    "ppiPlus" INTEGER NOT NULL,
    "dryerSkew" DOUBLE PRECISION NOT NULL,
    "sanfoSkew" DOUBLE PRECISION NOT NULL,
    "afterWashSkew" DOUBLE PRECISION NOT NULL,
    "bowingTestRightHand" DOUBLE PRECISION NOT NULL,
    "bowingTestLeftHand" DOUBLE PRECISION NOT NULL,
    "washWidthPercentage" DOUBLE PRECISION NOT NULL,
    "washLengthPercentage" DOUBLE PRECISION NOT NULL,
    "washShrinkageWidth" TEXT NOT NULL,
    "washShrinkagePPI" INTEGER NOT NULL,
    "processingDetails" TEXT NOT NULL,
    "remarks" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SampleData_pkey" PRIMARY KEY ("id")
);